name: Bug Report
description: Report a bug or issue
title: "[BUG] "
labels: ["bug"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting an issue! Please provide as much detail as possible.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Clear description of the bug
      placeholder: |
        The bot doesn't...
        Expected behavior...
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the issue
      placeholder: |
        1. 
        2. 
        3. 
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should happen
      placeholder: The bot should...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happens
      placeholder: Instead, it...
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs/Error Messages
      description: Error messages, stack traces, or logs
      render: python

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - Linux
        - macOS
        - Windows
        - Raspberry Pi / ARM
        - Docker
        - Other
    validations:
      required: true

  - type: input
    id: python_version
    attributes:
      label: Python Version
      placeholder: "3.7, 3.8, 3.9, 3.10, 3.11, etc."
    validations:
      required: true

  - type: input
    id: bot_version
    attributes:
      label: Bot Version
      placeholder: "1.0.0"
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment Details
      description: Any relevant environment information
      placeholder: |
        - Virtual environment: Yes/No
        - Docker: Yes/No
        - Database: PostgreSQL/None/etc.

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context about the problem
