name: Feature Request
description: Suggest a new feature or enhancement
title: "[FEATURE] "
labels: ["enhancement"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please describe your idea in detail.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Clear description of the feature
      placeholder: |
        I would like to add...
        This feature would help with...
    validations:
      required: true

  - type: textarea
    id: use_case
    attributes:
      label: Use Case
      description: What problem does this solve?
      placeholder: |
        Current behavior: ...
        Desired behavior: ...
    validations:
      required: true

  - type: textarea
    id: examples
    attributes:
      label: Examples
      description: Code examples or mockups
      render: python
      placeholder: |
        # How the feature would be used:
        bot.new_feature()

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: Alternative solutions you considered
      placeholder: |
        1. 
        2. 

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - Low
        - Medium
        - High
        - Critical
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other relevant information
